export default {
  FETCH_NOW_PLAYING: "FETCH_NOW_PLAYING",
  FETCH_NOW_PLAYING_SUCCESS: "FETCH_NOW_PLAYING_SUCCESS",

  FETCH_POPULAR: "FETCH_POPULAR",
  FETCH_POPULAR_SUCCESS: "FETCH_POPULAR_SUCCESS",
};
