export default {
  FETCH_NOW_PLAYING: "FETCH_NOW_PLAYING",
  FETCH_NOW_PLAYING_SUCCESS: "FETCH_NOW_PLAYING_SUCCESS",

  FETCH_POPULAR: "FETCH_POPULAR",
  FETCH_POPULAR_SUCCESS: "FETCH_POPULAR_SUCCESS",

  FETCH_TOP_RATED: "FETCH_TOP_RATED",
  FETCH_TOP_RATED_SUCCESS: "FETCH_TOP_RATED_SUCCESS",

  FETCH_TOP_RATED: "FETCH_TOP_RATED",
  FETCH_TOP_RATED_SUCCESS: "FETCH_TOP_RATED_SUCCESS",

  FETCH_RECOMMENDATION: "FETCH_RECOMMENDATION",
  FETCH_RECOMMENDATION_SUCCESS: "FETCH_RECOMMENDATION_SUCCESS",

  FETCH_IMAGE: "FETCH_IMAGE",
  FETCH_IMAGE_SUCCESS: "FETCH_IMAGE_SUCCESS",

  FETCH_DETAIL: "FETCH_DETAIL",
  FETCH_DETAIL_SUCCESS: "FETCH_DETAIL_SUCCESS",
};
