export default {
  SEARCH_BY_TITLE: "SEARCH_BY_TITLE",
  SEARCH_BY_TITLE_SUCCESS: "SEARCH_BY_TITLE_SUCCESS",

  SEARCH_BY_PEOPLE: "SEARCH_BY_PEOPLE",
  SEARCH_BY_PEOPLE_SUCCESS: "SEARCH_BY_PEOPLE_SUCCESS",
};
